import AppKit
import Testing
import ClipboardCore
@testable import ClipboardMac

@MainActor
struct ClipboardTests {
    private func withPasteboard(_ test: (NSPasteboard) throws -> Void) rethrows {
        let board = NSPasteboard(name: .init("Clipglass.tests.\(UUID())"))
        defer { board.releaseGlobally() }
        try test(board)
    }
    @Test func preservesMultipleItemsAndRepresentations() throws {
        try withPasteboard { board in
            let clip = Clip(title: "Hello", kind: "Text", payloads: [
                [NSPasteboard.PasteboardType.string.rawValue: Data("Hello".utf8), NSPasteboard.PasteboardType.html.rawValue: Data("<b>Hello</b>".utf8)],
                [NSPasteboard.PasteboardType.fileURL.rawValue: Data("file:///tmp/example.txt".utf8)]])
            #expect(ClipboardCodec.write(clip, to: board))
            let result = try #require(ClipboardCodec.read(from: board, byteLimit: 4096))
            #expect(result.payloads == clip.payloads)
            #expect(result.kind == "File")
        }
    }
    @Test(arguments: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"])
    func skipsPrivateContent(_ marker: String) {
        withPasteboard { board in
            board.setString("secret", forType: .string)
            board.setData(Data(), forType: .init(marker))
            #expect(ClipboardCodec.read(from: board, byteLimit: 4096) == nil)
        }
    }
    @Test func skipsOversizedAndUnsupportedContent() {
        withPasteboard { board in
            board.setString("too large", forType: .string)
            #expect(ClipboardCodec.read(from: board, byteLimit: 2) == nil)
            board.clearContents()
            board.setData(Data([1]), forType: .init("custom.unsupported"))
            #expect(ClipboardCodec.read(from: board, byteLimit: 4096) == nil)
        }
    }
    @Test func pauseResumeAndSelfCopyDoNotCreateHistoryEntries() throws {
        try withPasteboard { board in
            let store = ClipboardStore(pasteboard: board)
            board.clearContents()
            board.setString("first", forType: .string)
            store.captureClipboard()
            #expect(store.history.clips.count == 1)
            store.isPaused = true
            board.clearContents(); board.setString("paused", forType: .string)
            store.captureClipboard()
            store.isPaused = false
            store.captureClipboard()
            #expect(store.history.clips.count == 1)
            let first = try #require(store.history.clips.first)
            _ = store.copy(first)
            store.captureClipboard()
            #expect(store.history.clips.count == 1)
        }
    }
}
