import AppKit
import ClipboardCore

@MainActor
public enum ClipboardCodec {
    public static let supportedTypes: [NSPasteboard.PasteboardType] = [.string, .rtf, .html, .png, .tiff, .fileURL, .URL]
    private static let privateTypes = Set(["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"])

    public static func read(from pasteboard: NSPasteboard, byteLimit: Int) -> Clip? {
        let items = pasteboard.pasteboardItems ?? []
        guard !items.contains(where: { $0.types.contains { privateTypes.contains($0.rawValue) } }) else { return nil }
        var total = 0
        var payloads: [[String: Data]] = []
        for item in items {
            var payload: [String: Data] = [:]
            for type in supportedTypes {
                guard let bytes = item.data(forType: type) else { continue }
                guard bytes.count <= byteLimit - total else { return nil }
                total += bytes.count
                payload[type.rawValue] = bytes
            }
            if !payload.isEmpty { payloads.append(payload) }
        }
        guard !payloads.isEmpty else { return nil }
        let kind = kind(of: payloads)
        let title = title(from: pasteboard, kind: kind, count: payloads.count)
        return Clip(title: title, kind: kind, payloads: payloads)
    }

    @discardableResult public static func write(_ clip: Clip, to pasteboard: NSPasteboard) -> Bool {
        let items = clip.payloads.map { payload in
            let item = NSPasteboardItem()
            for (type, bytes) in payload { item.setData(bytes, forType: .init(type)) }
            return item
        }
        pasteboard.clearContents()
        return pasteboard.writeObjects(items)
    }

    private static func kind(of payloads: [[String: Data]]) -> String {
        if payloads.contains(where: { $0[NSPasteboard.PasteboardType.fileURL.rawValue] != nil }) { return "File" }
        if payloads.contains(where: { $0[NSPasteboard.PasteboardType.png.rawValue] != nil || $0[NSPasteboard.PasteboardType.tiff.rawValue] != nil }) { return "Image" }
        if payloads.contains(where: { $0[NSPasteboard.PasteboardType.URL.rawValue] != nil }) { return "Link" }
        return "Text"
    }

    private static func title(from pasteboard: NSPasteboard, kind: String, count: Int) -> String {
        if kind == "File", let path = pasteboard.string(forType: .fileURL), let url = URL(string: path) {
            return count == 1 ? url.lastPathComponent : "\(url.lastPathComponent) + \(count - 1) more"
        }
        return pasteboard.string(forType: .string) ?? pasteboard.string(forType: .URL) ?? (kind == "Image" ? "Copied image" : "Rich text")
    }
}
